name: .NET

on: 
  workflow_dispatch:
    branches: [ "move" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore ./SpaceBattle.Lib
      - name: Build
        run: dotnet build ./SpaceBattle.Lib --configuration Release --no-restore
      - name: Test
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=../coverage/ -p:CoverletOutputFormat=opencover --no-build --verbosity d ./SpaceBattle.Lib.Test
      - name: Codecov
        uses: codecov/codecov-action@v3

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: feature_1  #fill in your own flag name
      paths: 
      - src/feature_1  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: feature_2 #fill in your own flag name
      paths: 
      - src/feature_2  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
      - type: project
        target: 20%
      - type: patch
        target: 100%